/*
 * LoadTest.V1
 *
 * No description
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// An object designed to be medium sized
type MediumSized struct {

	Name string `json:"name"`

	Surname string `json:"surname"`

	Address string `json:"address,omitempty"`

	Location string `json:"location"`

	Country string `json:"country,omitempty"`

	Age float32 `json:"age,omitempty"`

	BirthDate time.Time `json:"birthDate,omitempty"`

	StartDate time.Time `json:"startDate,omitempty"`

	Type_ string `json:"Type,omitempty"`
}
