/*
 * LoadTest.V1
 *
 * No description
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LargeSizeGroup struct {

	// for all the big things
	ManyLargeSizeItems []LargeSized `json:"manyLargeSizeItems,omitempty"`

	// there won't be one
	Reason string `json:"reason,omitempty"`
}
