/*
 * LoadTest.V1
 *
 * No description
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// for bigger items
type LargeSized struct {

	One float32 `json:"one,omitempty"`

	Two int32 `json:"two,omitempty"`

	Three bool `json:"three,omitempty"`

	Four *User `json:"four,omitempty"`

	Five string `json:"five,omitempty"`

	Six *Users `json:"six,omitempty"`

	Seven *MediumSized `json:"seven,omitempty"`

	BiggerThan100 string `json:"biggerThan100,omitempty"`

	Nine string `json:"nine,omitempty"`

	Ten string `json:"ten,omitempty"`

	Eleven string `json:"eleven,omitempty"`

	Twelve string `json:"twelve,omitempty"`

	Thirteen string `json:"thirteen,omitempty"`

	Fourteen string `json:"fourteen,omitempty"`

	Fifteen string `json:"fifteen,omitempty"`

	Sixteen string `json:"sixteen,omitempty"`

	Seventeen string `json:"seventeen,omitempty"`

	Eighteen string `json:"eighteen,omitempty"`

	Nineteen string `json:"nineteen,omitempty"`

	Twenty string `json:"twenty,omitempty"`

	TwentyOne string `json:"twenty-one,omitempty"`

	TwentyTwo string `json:"twenty-two,omitempty"`

	TwentyThree string `json:"twenty-three,omitempty"`

	TwentyFour string `json:"twenty-four,omitempty"`

	TwentyFive string `json:"twenty-five,omitempty"`
}
