/*
 * LoadTest.V1
 *
 * No description
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"GetSmallUser",
		strings.ToUpper("Get"),
		"/small/{userID}",
		GetSmallUser,
	},

	Route{
		"HeadersDelete",
		strings.ToUpper("Delete"),
		"/headers",
		HeadersDelete,
	},

	Route{
		"HeadersGet",
		strings.ToUpper("Get"),
		"/headers",
		HeadersGet,
	},

	Route{
		"LargeSizedGet",
		strings.ToUpper("Get"),
		"/largeSized",
		LargeSizedGet,
	},

	Route{
		"LargeSizedLargeIdGet",
		strings.ToUpper("Get"),
		"/largeSized/{largeId}",
		LargeSizedLargeIdGet,
	},

	Route{
		"LargeSizedPost",
		strings.ToUpper("Post"),
		"/largeSized",
		LargeSizedPost,
	},

	Route{
		"MediumSizedGet",
		strings.ToUpper("Get"),
		"/mediumSized",
		MediumSizedGet,
	},

	Route{
		"MediumSizedMediumIdDelete",
		strings.ToUpper("Delete"),
		"/mediumSized/{mediumId}",
		MediumSizedMediumIdDelete,
	},

	Route{
		"MediumSizedPost",
		strings.ToUpper("Post"),
		"/mediumSized",
		MediumSizedPost,
	},

	Route{
		"ResponseCodeCheckGet",
		strings.ToUpper("Get"),
		"/responseCodeCheck",
		ResponseCodeCheckGet,
	},

	Route{
		"SlowGet",
		strings.ToUpper("Get"),
		"/slow",
		SlowGet,
	},

	Route{
		"SlowPost",
		strings.ToUpper("Post"),
		"/slow",
		SlowPost,
	},

	Route{
		"SmallGet",
		strings.ToUpper("Get"),
		"/small",
		SmallGet,
	},

	Route{
		"SmallUserIDDelete",
		strings.ToUpper("Delete"),
		"/small/{userID}",
		SmallUserIDDelete,
	},

	Route{
		"SmallUserIDPost",
		strings.ToUpper("Post"),
		"/small/{userID}",
		SmallUserIDPost,
	},

	Route{
		"TimeoutGet",
		strings.ToUpper("Get"),
		"/timeout",
		TimeoutGet,
	},
}
