/*
 * LoadTest.V1
 *
 * No description
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "Tutorial/LoadTest/swagger"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServeTLS(":11000", "./loadtest.cer", "./loadtest.pkcs8", router))
	//log.Fatal(http.ListenAndServe(":11000", router))
}
